### ISSUE TITLE
Licence file

### ISSUE THREAD

**Issue by sjanssen2** [JonasKup/FlowSoFine#1]
Hi Jonas,
we need a licence and a licence file for a proper conda recipe. I'd recommend GPL-3.

**Comment by JonasKup** [comment]
Yes, GPL-3 sounds good. The License is specified in the Description file https://github.com/JonasKup/FlowSoFine/blob/master/DESCRIPTION

**Comment by sjanssen2** [comment]
Bioconda forces us to have a LICENCE file

JonasKup <notifications@github.com> schrieb am Di., 2. März 2021, 07:36:
